(executable
 (name softmax_profile)
 (modules softmax_profile)
 (enabled_if
  (= %{env:RUNE_PJRT_CUDA_KERNELS=disabled} enabled))
 (libraries rune_pjrt nx rune unix)
 (link_deps ../kernels/causal_scaled_softmax.so)
 (preprocess
  (pps ppx_rune_kernel)))

(executable
 (name triton_profile)
 (modules triton_profile)
 (enabled_if
  (= %{env:RUNE_PJRT_CUDA_KERNELS=disabled} enabled))
 (libraries rune_pjrt nx rune unix)
 (preprocess
  (pps ppx_rune_kernel)))
